"""add pmid doi all_authors fields

Revision ID: 5474eda25abe
Revises: ef78ca32349c
Create Date: 2026-03-12 14:29:56.695321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5474eda25abe'
down_revision: Union[str, Sequence[str], None] = 'ef78ca32349c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_leads', sa.Column('pmid', sa.Text(), nullable=True))
    op.add_column('paper_leads', sa.Column('doi', sa.Text(), nullable=True))
    op.add_column('paper_leads', sa.Column('all_authors', sa.Text(), nullable=True))
    op.create_index('ix_paper_leads_pmid', 'paper_leads', ['pmid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_leads_pmid', table_name='paper_leads')
    op.drop_column('paper_leads', 'all_authors')
    op.drop_column('paper_leads', 'doi')
    op.drop_column('paper_leads', 'pmid')
    # ### end Alembic commands ###
