"""Initial tables

Revision ID: ef78ca32349c
Revises: 
Create Date: 2026-03-11 19:43:26.752252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef78ca32349c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawled_urls',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('paper_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('keywords_matched', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=1), nullable=True),
    sa.Column('feedback_status', sa.String(length=20), nullable=True),
    sa.Column('strategy_version', sa.String(length=10), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('ix_paper_leads_created_at', 'paper_leads', ['created_at'], unique=False)
    op.create_index('ix_paper_leads_feedback_status', 'paper_leads', ['feedback_status'], unique=False)
    op.create_index('ix_paper_leads_grade', 'paper_leads', ['grade'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('tender_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('announcement_id', sa.Text(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('org_only', sa.Boolean(), nullable=False),
    sa.Column('budget_info', sa.Text(), nullable=True),
    sa.Column('keywords_matched', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=1), nullable=True),
    sa.Column('feedback_status', sa.String(length=20), nullable=True),
    sa.Column('strategy_version', sa.String(length=10), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('ix_tender_leads_created_at', 'tender_leads', ['created_at'], unique=False)
    op.create_index('ix_tender_leads_feedback_status', 'tender_leads', ['feedback_status'], unique=False)
    op.create_index('ix_tender_leads_grade', 'tender_leads', ['grade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tender_leads_grade', table_name='tender_leads')
    op.drop_index('ix_tender_leads_feedback_status', table_name='tender_leads')
    op.drop_index('ix_tender_leads_created_at', table_name='tender_leads')
    op.drop_table('tender_leads')
    op.drop_table('strategy_versions')
    op.drop_index('ix_paper_leads_grade', table_name='paper_leads')
    op.drop_index('ix_paper_leads_feedback_status', table_name='paper_leads')
    op.drop_index('ix_paper_leads_created_at', table_name='paper_leads')
    op.drop_table('paper_leads')
    op.drop_table('crawled_urls')
    # ### end Alembic commands ###
